# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yVuMF-24w0h-AFzwpwAkGdJLqXcFffwu
"""

import streamlit as st
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler

st.title("Dhaka AQI Forecaster (Simple Version)")
st.write("Enter expected weather conditions to get a predicted AQI")

# Dummy training data (real app-এ তোমার ডেটা দিয়ে ট্রেইন করতে পারো)
# Features: temp, rain, lag1 (previous AQI), season
X_dummy = np.array([
    [30, 0, 100, 3], [28, 5, 120, 2], [25, 10, 80, 1],
    [35, 0, 150, 4], [22, 20, 90, 2], [32, 2, 110, 3],
    [33, 3, 130, 3], [27, 15, 95, 1], [31, 1, 115, 3]
])
y_dummy = np.array([120, 140, 90, 180, 70, 130, 145, 85, 135])  # Dummy AQI values

# Train a simple model (runs once when app starts)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_dummy)

model = GradientBoostingRegressor(n_estimators=50, random_state=42)
model.fit(X_scaled, y_dummy)

st.info("Model trained with dummy data (for demo). In real app use your actual data.")

# User inputs
temp = st.number_input("Expected Average Temperature (°C)", 10.0, 40.0, 28.0)
rain = st.number_input("Expected Rainfall (mm)", 0.0, 100.0, 0.0)
lag1 = st.number_input("Previous Day AQI (approx)", 0.0, 500.0, 100.0)
season = st.slider("Season (1=Winter, 4=Summer)", 1, 4, 3)

if st.button("Predict AQI"):
    try:
        # Prepare input
        input_data = np.array([[temp, rain, lag1, season]])
        input_scaled = scaler.transform(input_data)

        # Predict
        pred_aqi = model.predict(input_scaled)[0]

        st.success(f"**Predicted AQI: {int(pred_aqi)}**")

        if pred_aqi > 150:
            st.warning("**Health Advice**: Wear N95 mask outdoors, limit physical activity, sensitive groups stay indoors.")
        elif pred_aqi > 100:
            st.info("**Moderate pollution** — Consider reducing outdoor time if sensitive.")
        else:
            st.success("**Good air quality** today — safe to go outside!")

    except Exception as e:
        st.error(f"Error: {str(e)}\nPlease check inputs or contact support.")